version: '3.9'

services:

  lava-node:
    image: eth2dev/lava:v1.2.3
    container_name: 'lavad'
    volumes:
      - ${NODEDATA_DIR:-./data}:/root/.lava/data
      - ${NODECFG_DIR:-./config}:/root/.lava/config
    environment:
      - LAVA_LISTEN_IP=${LAVA_LISTEN_IP:-0.0.0.0}
      - LAVA_LOG_LEVEL=${LAVA_LOG_LEVEL:-info}
      - LAVA_CHAIN_ID=${LAVA_CHAIN_ID:-lava-testnet-2}
      - LAVA_MONIKER=${LAVA_MONIKER:-zkweb3xyz}
    ports:
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_API:-1317}:1317'
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_GRPC:-9090}:9090'
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_GRPC_WEB:-9091}:9091'
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_P2P:-26656}:26656'
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_RPC:-26657}:26657'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    restart: on-failure:5
