name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - name: Set the value
      run: |
        echo "git_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))" >> "$GITHUB_ENV"
    - name: Use the value
      run: |
        printf '%s\n' "$git_tag"
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . -f Dockerfile -t eth2dev/lava:$git_tag
    - name: Docker image push
      run: docker push eth2dev/lava:$git_tag
